export type InstagramPost = {
  id: string;
  url: string;
  image: string;
  caption: string;
  publishedAt: string | null;
};

// JSON Feed (v1.1) for instagram.com/xymiku.39, generated by RSS.app since
// Instagram has no native feed. This tier's feed caps at 6 items — getting
// more requires upgrading the RSS.app plan for this feed.
//
// Fetched only at build time (static export): the photo URLs are signed
// Instagram CDN links that expire after a few days, so this section only
// stays fresh across redeploys, not indefinitely. See the scheduled-rebuild
// setup (README) for keeping it current automatically.
const FEED_URL = "https://rss.app/feeds/v1.1/9NH3qtc3KAQCoiuj.json";

type JsonFeedItem = {
  id: string;
  url: string;
  title?: string;
  content_text?: string;
  image?: string;
  date_published?: string;
};

type JsonFeed = {
  items?: JsonFeedItem[];
};

export async function getInstagramFeed(): Promise<InstagramPost[]> {
  try {
    const res = await fetch(FEED_URL);
    if (!res.ok) return [];
    const data = (await res.json()) as JsonFeed;

    return (data.items ?? [])
      .filter((item): item is JsonFeedItem & { image: string } => Boolean(item.image))
      .map((item) => ({
        id: item.id,
        url: item.url,
        image: item.image,
        caption: (item.content_text ?? item.title ?? "").trim(),
        publishedAt: item.date_published ?? null,
      }));
  } catch {
    return [];
  }
}
